### ISSUE TITLE
Hera is reassigning people for PRs that have a "Merge It" tag

### ISSUE THREAD

**Issue by Garrett-R** [plangrid/hera#17]
As you can see we have some bad news:

![hera_problem](https://cloud.githubusercontent.com/assets/6614695/11759606/ae270a66-a032-11e5-9652-170cdb23cec8.png)

With a `Merge It!` tag, it's re-assigning to someone else.

@oahayder ^

**Comment by jpalawaga** [comment]
hera assigns based on the `needs review` tags i think.

i had this issue. reapplying the needs review tag and removing it seemed to clear it up for me. does seem to be a bug though

**Comment by oahayder** [comment]
@Garrett-R @jpalawaga This could be from Liz's latest change where she made Hera assign double reviewers %50 of the time. We should also be adjusting the labels... Let me look into it when I get back

https://github.com/plangrid/hera/commit/d605cba10a36bff13ab538cbeb9347209830b8c3

**Comment by Garrett-R** [comment]
:+1:
